--- #YAML:1.0
name:               Bio-DB-NextProt
version:            1.02
abstract:           Object interface to NextProt REST API.
author:
    - Felipe da Veiga Leprevost <leprevost@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Net::FTP::Tiny:  0
    Test::More:      0
requires:
    perl:          5.012
    REST::Client:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
